import '~/styles/globals.css';

import React from 'react';

import Header from '~/app/_components/Header';
import LayoutBody from '~/app/_layouts/LayoutBody';
import RootLayoutRoot from '~/app/_layouts/RootLayoutRoot';

export const metadata = {
  title: 'Food Ai',
  description: 'Generated by create-t3-app',
  icons: [{ rel: 'icon', url: '/favicon.ico' }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <RootLayoutRoot>
      <Header />
      <LayoutBody>{children}</LayoutBody>
    </RootLayoutRoot>
  );
}
